import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Define metadata outside the component
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ isolation: "isolate" }} // Move isolation here, check if necessary
      >
        {children}
      </body>
    </html>
  );
}
